# Generated by Django 4.2.4 on 2023-08-09 11:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50, verbose_name='страна')),
                ('city', models.CharField(max_length=50, verbose_name='город')),
                ('address', models.CharField(max_length=100, verbose_name='адрес')),
                ('phone_number', models.CharField(max_length=20, verbose_name='номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='адрес электронной почты')),
            ],
            options={
                'verbose_name': 'контакт',
                'verbose_name_plural': 'контакты',
            },
        ),
        migrations.CreateModel(
            name='Migration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('applied', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'миграция',
                'verbose_name_plural': 'миграции',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='last_change',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='дата последнего изменения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='produce_day',
            field=models.DateField(default='2022-01-01', verbose_name='дата создания'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_price',
            field=models.IntegerField(default=django.utils.timezone.now, verbose_name='цена за покупку'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='изображение (превью)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='наименование'),
        ),
    ]
