# Generated by Django 4.2.4 on 2023-08-09 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_yourmodel_alter_product_last_change_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Migration',
        ),
        migrations.AlterField(
            model_name='product',
            name='produce_day',
            field=models.DateField(default=datetime.date(2022, 1, 1), verbose_name='дата создания'),
        ),
    ]
